// Dummy data for Jira-like project table
export const initialProjects = [
  {
    id: '1',
    projectName: 'Residential Complex Alpha',
    referenceNumber: 'REF-001',
    status: 'In Progress',
    owner: 'John Smith',
    timeline: { startDate: '2024-01-15', endDate: '2024-06-30' },
    planDays: 165,
    remarks: 'High priority residential project',
    assigneeNotes: 'Foundation work completed. Moving to structural phase.',
    attachments: [
      { name: 'blueprint.pdf', size: '2.3MB' },
      { name: 'site-survey.docx', size: '1.1MB' }
    ],
    priority: 'High',
    location: 'Downtown District',
    plotNumber: 'PL-2024-001',
    community: 'Green Valley',
    projectType: 'Residential',
    projectFloor: 15,
    developer: 'Alpha Developers Ltd',
    projectAutoPredecessor: 'REF-000',
    checklist: [
      { id: 1, text: 'Site survey completed', completed: true },
      { id: 2, text: 'Permits obtained', completed: true },
      { id: 3, text: 'Foundation work', completed: true },
      { id: 4, text: 'Structural framework', completed: false },
      { id: 5, text: 'Interior finishing', completed: false }
    ],
    link: 'https://project-alpha.com',
    rating: 4,
    progress: 35,
    colorIndicator: '#3B82F6',
    subtasks: [
      {
        id: '1-1',
        projectName: 'Foundation Work',
        referenceNumber: 'REF-001-01',
        status: 'Done',
        owner: 'Mike Johnson',
        timeline: { startDate: '2024-01-15', endDate: '2024-02-28' },
        planDays: 45,
        remarks: 'Foundation completed ahead of schedule',
        assigneeNotes: 'All foundation work completed successfully',
        attachments: [{ name: 'foundation-report.pdf', size: '0.8MB' }],
        priority: 'High',
        location: 'Downtown District',
        plotNumber: 'PL-2024-001',
        community: 'Green Valley',
        projectType: 'Residential',
        projectFloor: 1,
        developer: 'Alpha Developers Ltd',
        projectAutoPredecessor: 'REF-001',
        checklist: [
          { id: 1, text: 'Excavation', completed: true },
          { id: 2, text: 'Reinforcement', completed: true },
          { id: 3, text: 'Concrete pouring', completed: true }
        ],
        link: 'https://project-alpha.com/foundation',
        rating: 5,
        progress: 100,
        colorIndicator: '#10B981'
      },
      {
        id: '1-2',
        projectName: 'Structural Framework',
        referenceNumber: 'REF-001-02',
        status: 'In Progress',
        owner: 'Sarah Wilson',
        timeline: { startDate: '2024-03-01', endDate: '2024-04-30' },
        planDays: 60,
        remarks: 'Steel framework installation in progress',
        assigneeNotes: '50% of structural work completed',
        attachments: [{ name: 'structural-plan.pdf', size: '3.2MB' }],
        priority: 'High',
        location: 'Downtown District',
        plotNumber: 'PL-2024-001',
        community: 'Green Valley',
        projectType: 'Residential',
        projectFloor: 15,
        developer: 'Alpha Developers Ltd',
        projectAutoPredecessor: 'REF-001-01',
        checklist: [
          { id: 1, text: 'Steel beams installation', completed: true },
          { id: 2, text: 'Column erection', completed: true },
          { id: 3, text: 'Floor slabs', completed: false },
          { id: 4, text: 'Roof structure', completed: false }
        ],
        link: 'https://project-alpha.com/structural',
        rating: 4,
        progress: 50,
        colorIndicator: '#F59E0B'
      }
    ]
  },
  {
    id: '2',
    projectName: 'Commercial Plaza Beta',
    referenceNumber: 'REF-002',
    status: 'Done',
    owner: 'Emily Davis',
    timeline: { startDate: '2023-08-01', endDate: '2024-02-28' },
    planDays: 212,
    remarks: 'Modern commercial complex with retail and office spaces',
    assigneeNotes: 'Project completed successfully. All tenants moved in.',
    attachments: [
      { name: 'commercial-design.pdf', size: '4.1MB' },
      { name: 'tenant-agreements.pdf', size: '2.8MB' }
    ],
    priority: 'Medium',
    location: 'Business District',
    plotNumber: 'PL-2023-002',
    community: 'Central Business',
    projectType: 'Commercial',
    projectFloor: 12,
    developer: 'Beta Properties Inc',
    projectAutoPredecessor: 'REF-001',
    checklist: [
      { id: 1, text: 'Design approval', completed: true },
      { id: 2, text: 'Construction', completed: true },
      { id: 3, text: 'Interior finishing', completed: true },
      { id: 4, text: 'Tenant fit-out', completed: true },
      { id: 5, text: 'Final inspection', completed: true }
    ],
    link: 'https://project-beta.com',
    rating: 5,
    progress: 100,
    colorIndicator: '#10B981'
  },
  {
    id: '3',
    projectName: 'Luxury Hotel Gamma',
    referenceNumber: 'REF-003',
    status: 'In Progress',
    owner: 'David Brown',
    timeline: { startDate: '2024-02-01', endDate: '2024-11-30' },
    planDays: 304,
    remarks: '5-star luxury hotel with premium amenities',
    assigneeNotes: 'Structural work 60% complete. Starting interior work.',
    attachments: [
      { name: 'hotel-design.pdf', size: '5.7MB' },
      { name: 'amenities-list.pdf', size: '1.9MB' }
    ],
    priority: 'High',
    location: 'Tourist District',
    plotNumber: 'PL-2024-003',
    community: 'Tourist Hub',
    projectType: 'Hospitality',
    projectFloor: 20,
    developer: 'Gamma Hospitality Group',
    projectAutoPredecessor: 'REF-002',
    checklist: [
      { id: 1, text: 'Foundation work', completed: true },
      { id: 2, text: 'Structural framework', completed: true },
      { id: 3, text: 'Exterior finishing', completed: false },
      { id: 4, text: 'Interior design', completed: false },
      { id: 5, text: 'Amenities installation', completed: false }
    ],
    link: 'https://project-gamma.com',
    rating: 4,
    progress: 60,
    colorIndicator: '#F59E0B'
  },
  {
    id: '4',
    projectName: 'Industrial Warehouse Delta',
    referenceNumber: 'REF-004',
    status: 'To Do',
    owner: 'Mike Johnson',
    timeline: { startDate: '2024-05-01', endDate: '2024-10-31' },
    planDays: 184,
    remarks: 'Large-scale industrial warehouse for logistics',
    assigneeNotes: 'Planning phase completed. Ready to start construction.',
    attachments: [
      { name: 'warehouse-plan.pdf', size: '3.4MB' },
      { name: 'logistics-study.pdf', size: '1.2MB' }
    ],
    priority: 'Medium',
    location: 'Industrial Zone',
    plotNumber: 'PL-2024-004',
    community: 'Industrial Park',
    projectType: 'Industrial',
    projectFloor: 3,
    developer: 'Delta Construction Co',
    projectAutoPredecessor: 'REF-003',
    checklist: [
      { id: 1, text: 'Site preparation', completed: false },
      { id: 2, text: 'Foundation work', completed: false },
      { id: 3, text: 'Warehouse structure', completed: false },
      { id: 4, text: 'Loading docks', completed: false },
      { id: 5, text: 'Final inspection', completed: false }
    ],
    link: 'https://project-delta.com',
    rating: 3,
    progress: 5,
    colorIndicator: '#6B7280'
  },
  {
    id: '5',
    projectName: 'Mixed-Use Complex Epsilon',
    referenceNumber: 'REF-005',
    status: 'In Progress',
    owner: 'Sarah Wilson',
    timeline: { startDate: '2024-01-01', endDate: '2024-12-31' },
    planDays: 366,
    remarks: 'Residential and commercial mixed-use development',
    assigneeNotes: 'Phase 1 completed. Starting Phase 2 construction.',
    attachments: [
      { name: 'mixed-use-design.pdf', size: '6.2MB' },
      { name: 'phase-planning.pdf', size: '2.1MB' }
    ],
    priority: 'High',
    location: 'Downtown District',
    plotNumber: 'PL-2024-005',
    community: 'Sunset Hills',
    projectType: 'Residential',
    projectFloor: 18,
    developer: 'Epsilon Real Estate',
    projectAutoPredecessor: 'REF-004',
    checklist: [
      { id: 1, text: 'Phase 1 foundation', completed: true },
      { id: 2, text: 'Phase 1 structure', completed: true },
      { id: 3, text: 'Phase 2 foundation', completed: false },
      { id: 4, text: 'Phase 2 structure', completed: false },
      { id: 5, text: 'Final finishing', completed: false }
    ],
    link: 'https://project-epsilon.com',
    rating: 4,
    progress: 45,
    colorIndicator: '#F59E0B'
  },
  {
    id: '6',
    projectName: 'Shopping Mall Zeta',
    referenceNumber: 'REF-006',
    status: 'Done',
    owner: 'Lisa Anderson',
    timeline: { startDate: '2023-06-01', endDate: '2024-01-31' },
    planDays: 245,
    remarks: 'Modern shopping mall with entertainment facilities',
    assigneeNotes: 'Project completed. All stores operational.',
    attachments: [
      { name: 'mall-design.pdf', size: '4.8MB' },
      { name: 'store-layout.pdf', size: '2.3MB' }
    ],
    priority: 'Medium',
    location: 'Business District',
    plotNumber: 'PL-2023-006',
    community: 'Central Business',
    projectType: 'Commercial',
    projectFloor: 8,
    developer: 'Zeta Retail Group',
    projectAutoPredecessor: 'REF-005',
    checklist: [
      { id: 1, text: 'Foundation work', completed: true },
      { id: 2, text: 'Mall structure', completed: true },
      { id: 3, text: 'Store fit-outs', completed: true },
      { id: 4, text: 'Entertainment area', completed: true },
      { id: 5, text: 'Grand opening', completed: true }
    ],
    link: 'https://project-zeta.com',
    rating: 5,
    progress: 100,
    colorIndicator: '#10B981'
  },
  {
    id: '7',
    projectName: 'Office Tower Eta',
    referenceNumber: 'REF-007',
    status: 'In Progress',
    owner: 'Robert Chen',
    timeline: { startDate: '2024-03-01', endDate: '2025-02-28' },
    planDays: 365,
    remarks: 'Premium office tower with smart building features',
    assigneeNotes: 'Structural work 40% complete. Installing smart systems.',
    attachments: [
      { name: 'office-design.pdf', size: '5.1MB' },
      { name: 'smart-systems.pdf', size: '1.8MB' }
    ],
    priority: 'High',
    location: 'Business District',
    plotNumber: 'PL-2024-007',
    community: 'Central Business',
    projectType: 'Commercial',
    projectFloor: 25,
    developer: 'Eta Office Solutions',
    projectAutoPredecessor: 'REF-006',
    checklist: [
      { id: 1, text: 'Foundation work', completed: true },
      { id: 2, text: 'Core structure', completed: true },
      { id: 3, text: 'Floor construction', completed: false },
      { id: 4, text: 'Smart systems', completed: false },
      { id: 5, text: 'Interior finishing', completed: false }
    ],
    link: 'https://project-eta.com',
    rating: 4,
    progress: 40,
    colorIndicator: '#F59E0B'
  },
  {
    id: '8',
    projectName: 'Residential Towers Theta',
    referenceNumber: 'REF-008',
    status: 'To Do',
    owner: 'Jennifer Martinez',
    timeline: { startDate: '2024-07-01', endDate: '2025-06-30' },
    planDays: 365,
    remarks: 'Twin residential towers with luxury amenities',
    assigneeNotes: 'Design phase in progress. Construction to start soon.',
    attachments: [
      { name: 'towers-design.pdf', size: '7.3MB' },
      { name: 'amenities-plan.pdf', size: '2.5MB' }
    ],
    priority: 'Medium',
    location: 'Residential Area',
    plotNumber: 'PL-2024-008',
    community: 'Riverside Park',
    projectType: 'Residential',
    projectFloor: 30,
    developer: 'Theta Luxury Homes',
    projectAutoPredecessor: 'REF-007',
    checklist: [
      { id: 1, text: 'Design approval', completed: true },
      { id: 2, text: 'Site preparation', completed: false },
      { id: 3, text: 'Foundation work', completed: false },
      { id: 4, text: 'Tower construction', completed: false },
      { id: 5, text: 'Amenities installation', completed: false }
    ],
    link: 'https://project-theta.com',
    rating: 3,
    progress: 15,
    colorIndicator: '#6B7280'
  },
  {
    id: '9',
    projectName: 'Medical Center Iota',
    referenceNumber: 'REF-009',
    status: 'In Progress',
    owner: 'Dr. Sarah Chen',
    timeline: { startDate: '2024-03-01', endDate: '2024-12-31' },
    planDays: 306,
    remarks: 'State-of-the-art medical center with advanced equipment',
    assigneeNotes: 'Structural work 70% complete. Starting medical equipment installation.',
    attachments: [
      { name: 'medical-design.pdf', size: '7.2MB' },
      { name: 'equipment-list.pdf', size: '1.5MB' }
    ],
    priority: 'High',
    location: 'Medical District',
    plotNumber: 'PL-2024-009',
    community: 'Health Valley',
    projectType: 'Healthcare',
    projectFloor: 8,
    developer: 'Iota Healthcare Ltd',
    projectAutoPredecessor: 'REF-008',
    checklist: [
      { id: 1, text: 'Site preparation', completed: true },
      { id: 2, text: 'Foundation work', completed: true },
      { id: 3, text: 'Structural framework', completed: true },
      { id: 4, text: 'Medical equipment', completed: false },
      { id: 5, text: 'Final inspection', completed: false }
    ],
    link: 'https://project-iota.com',
    rating: 4,
    progress: 70,
    colorIndicator: '#F59E0B'
  },
  {
    id: '10',
    projectName: 'Educational Campus Kappa',
    referenceNumber: 'REF-010',
    status: 'To Do',
    owner: 'Professor James Lee',
    timeline: { startDate: '2024-06-01', endDate: '2025-05-31' },
    planDays: 365,
    remarks: 'Modern educational campus with research facilities',
    assigneeNotes: 'Planning phase in progress. Construction to start soon.',
    attachments: [
      { name: 'campus-design.pdf', size: '8.1MB' },
      { name: 'research-facilities.pdf', size: '2.8MB' }
    ],
    priority: 'Medium',
    location: 'Educational District',
    plotNumber: 'PL-2024-010',
    community: 'Knowledge Park',
    projectType: 'Education',
    projectFloor: 6,
    developer: 'Kappa Education Corp',
    projectAutoPredecessor: 'REF-009',
    checklist: [
      { id: 1, text: 'Design approval', completed: true },
      { id: 2, text: 'Financial planning', completed: true },
      { id: 3, text: 'Site preparation', completed: false },
      { id: 4, text: 'Building construction', completed: false },
      { id: 5, text: 'Equipment installation', completed: false }
    ],
    link: 'https://project-kappa.com',
    rating: 3,
    progress: 10,
    colorIndicator: '#6B7280'
  },
  {
    id: '11',
    projectName: 'Sports Complex Lambda',
    referenceNumber: 'REF-011',
    status: 'In Progress',
    owner: 'Coach Michael Rodriguez',
    timeline: { startDate: '2024-04-01', endDate: '2024-11-30' },
    planDays: 244,
    remarks: 'Multi-sport complex with indoor and outdoor facilities',
    assigneeNotes: 'Outdoor facilities 80% complete. Starting indoor construction.',
    attachments: [
      { name: 'sports-design.pdf', size: '4.6MB' },
      { name: 'facilities-plan.pdf', size: '2.2MB' }
    ],
    priority: 'Medium',
    location: 'Sports District',
    plotNumber: 'PL-2024-011',
    community: 'Athletic Park',
    projectType: 'Recreation',
    projectFloor: 3,
    developer: 'Lambda Sports Group',
    projectAutoPredecessor: 'REF-010',
    checklist: [
      { id: 1, text: 'Site preparation', completed: true },
      { id: 2, text: 'Outdoor facilities', completed: true },
      { id: 3, text: 'Indoor structure', completed: false },
      { id: 4, text: 'Equipment installation', completed: false },
      { id: 5, text: 'Final testing', completed: false }
    ],
    link: 'https://project-lambda.com',
    rating: 4,
    progress: 65,
    colorIndicator: '#F59E0B'
  },
  {
    id: '12',
    projectName: 'Technology Park Mu',
    referenceNumber: 'REF-012',
    status: 'To Do',
    owner: 'Tech Director Alex Kim',
    timeline: { startDate: '2024-08-01', endDate: '2025-07-31' },
    planDays: 365,
    remarks: 'Innovation hub for tech startups and research centers',
    assigneeNotes: 'Design phase completed. Ready for construction.',
    attachments: [
      { name: 'tech-park-design.pdf', size: '6.8MB' },
      { name: 'innovation-centers.pdf', size: '3.1MB' }
    ],
    priority: 'High',
    location: 'Technology District',
    plotNumber: 'PL-2024-012',
    community: 'Innovation Valley',
    projectType: 'Commercial',
    projectFloor: 12,
    developer: 'Mu Technology Corp',
    projectAutoPredecessor: 'REF-011',
    checklist: [
      { id: 1, text: 'Design approval', completed: true },
      { id: 2, text: 'Site preparation', completed: false },
      { id: 3, text: 'Building construction', completed: false },
      { id: 4, text: 'Tech infrastructure', completed: false },
      { id: 5, text: 'Startup spaces', completed: false }
    ],
    link: 'https://project-mu.com',
    rating: 4,
    progress: 20,
    colorIndicator: '#6B7280'
  },
  {
    id: '13',
    projectName: 'Transportation Hub Nu',
    referenceNumber: 'REF-013',
    status: 'In Progress',
    owner: 'Transport Manager Maria Garcia',
    timeline: { startDate: '2024-02-01', endDate: '2024-10-31' },
    planDays: 274,
    remarks: 'Modern transportation hub connecting multiple transit systems',
    assigneeNotes: 'Structural work 55% complete. Installing transit systems.',
    attachments: [
      { name: 'transport-design.pdf', size: '5.4MB' },
      { name: 'transit-systems.pdf', size: '2.7MB' }
    ],
    priority: 'High',
    location: 'Transport District',
    plotNumber: 'PL-2024-013',
    community: 'Transit Center',
    projectType: 'Infrastructure',
    projectFloor: 5,
    developer: 'Nu Transport Solutions',
    projectAutoPredecessor: 'REF-012',
    checklist: [
      { id: 1, text: 'Foundation work', completed: true },
      { id: 2, text: 'Main structure', completed: true },
      { id: 3, text: 'Transit platforms', completed: false },
      { id: 4, text: 'System integration', completed: false },
      { id: 5, text: 'Final testing', completed: false }
    ],
    link: 'https://project-nu.com',
    rating: 4,
    progress: 55,
    colorIndicator: '#F59E0B'
  },
  {
    id: '14',
    projectName: 'Cultural Center Xi',
    referenceNumber: 'REF-014',
    status: 'Done',
    owner: 'Cultural Director Elena Petrova',
    timeline: { startDate: '2023-09-01', endDate: '2024-03-31' },
    planDays: 213,
    remarks: 'Multicultural center with theaters, galleries, and performance spaces',
    assigneeNotes: 'Project completed successfully. All facilities operational.',
    attachments: [
      { name: 'cultural-design.pdf', size: '4.9MB' },
      { name: 'facilities-guide.pdf', size: '1.6MB' }
    ],
    priority: 'Medium',
    location: 'Cultural District',
    plotNumber: 'PL-2023-014',
    community: 'Arts Quarter',
    projectType: 'Cultural',
    projectFloor: 6,
    developer: 'Xi Cultural Foundation',
    projectAutoPredecessor: 'REF-013',
    checklist: [
      { id: 1, text: 'Foundation work', completed: true },
      { id: 2, text: 'Main structure', completed: true },
      { id: 3, text: 'Performance spaces', completed: true },
      { id: 4, text: 'Gallery spaces', completed: true },
      { id: 5, text: 'Grand opening', completed: true }
    ],
    link: 'https://project-xi.com',
    rating: 5,
    progress: 100,
    colorIndicator: '#10B981'
  },
  {
    id: '15',
    projectName: 'Green Energy Plant Omicron',
    referenceNumber: 'REF-015',
    status: 'In Progress',
    owner: 'Energy Engineer Dr. Thomas Wang',
    timeline: { startDate: '2024-01-01', endDate: '2024-12-31' },
    planDays: 366,
    remarks: 'Renewable energy plant with solar and wind power generation',
    assigneeNotes: 'Solar panels 75% installed. Wind turbines next phase.',
    attachments: [
      { name: 'energy-design.pdf', size: '6.5MB' },
      { name: 'power-systems.pdf', size: '3.3MB' }
    ],
    priority: 'High',
    location: 'Energy District',
    plotNumber: 'PL-2024-015',
    community: 'Green Energy Park',
    projectType: 'Energy',
    projectFloor: 2,
    developer: 'Omicron Energy Solutions',
    projectAutoPredecessor: 'REF-014',
    checklist: [
      { id: 1, text: 'Site preparation', completed: true },
      { id: 2, text: 'Solar installation', completed: true },
      { id: 3, text: 'Wind turbines', completed: false },
      { id: 4, text: 'Power systems', completed: false },
      { id: 5, text: 'Grid connection', completed: false }
    ],
    link: 'https://project-omicron.com',
    rating: 4,
    progress: 75,
    colorIndicator: '#F59E0B'
  }
];

// Column definitions
export const columnDefinitions = [
  { key: 'projectName', label: 'Project Name', type: 'text', width: 200, sortable: true },
  { key: 'referenceNumber', label: 'Reference Number', type: 'text', width: 150, sortable: true },
  { key: 'status', label: 'Status', type: 'dropdown', width: 120, sortable: true, options: ['To Do', 'In Progress', 'Done'] },
  { key: 'owner', label: 'Owner', type: 'person', width: 150, sortable: true },
  { key: 'timeline', label: 'Timeline', type: 'daterange', width: 180, sortable: true },
  { key: 'planDays', label: 'Plan Days', type: 'number', width: 100, sortable: true },
  { key: 'remarks', label: 'Remarks', type: 'text', width: 200, sortable: false },
  { key: 'assigneeNotes', label: 'Assignee Notes', type: 'textarea', width: 250, sortable: false },
  { key: 'attachments', label: 'Attachments', type: 'file', width: 120, sortable: false },
  { key: 'priority', label: 'Priority', type: 'dropdown', width: 100, sortable: true, options: ['Low', 'Medium', 'High'] },
  { key: 'location', label: 'Location', type: 'text', width: 150, sortable: true },
  { key: 'plotNumber', label: 'Plot Number', type: 'text', width: 120, sortable: true },
  { key: 'community', label: 'Community', type: 'text', width: 150, sortable: true },
  { key: 'projectType', label: 'Project Type', type: 'dropdown', width: 140, sortable: true, options: ['Residential', 'Commercial', 'Hospitality', 'Industrial', 'Healthcare', 'Education', 'Recreation', 'Cultural', 'Energy', 'Infrastructure'] },
  { key: 'projectFloor', label: 'Project Floor', type: 'number', width: 100, sortable: true },
  { key: 'developer', label: 'Developer', type: 'text', width: 180, sortable: true },
  { key: 'projectAutoPredecessor', label: 'Auto Predecessor', type: 'text', width: 150, sortable: true },
  { key: 'checklist', label: 'Checklist', type: 'checklist', width: 150, sortable: false },
  { key: 'link', label: 'Link', type: 'url', width: 120, sortable: false },
  { key: 'rating', label: 'Rating', type: 'rating', width: 100, sortable: true },
  { key: 'progress', label: 'Progress', type: 'progress', width: 120, sortable: true },
  { key: 'colorIndicator', label: 'Color', type: 'color', width: 80, sortable: false }
];

// Sample data for auto-suggestions
export const autoSuggestData = {
  owners: ['John Smith', 'Emily Davis', 'David Brown', 'Mike Johnson', 'Sarah Wilson', 'Lisa Anderson', 'Robert Chen'],
  developers: ['Alpha Developers Ltd', 'Beta Properties Inc', 'Gamma Hospitality Group', 'Delta Construction Co', 'Epsilon Real Estate'],
  locations: ['Downtown District', 'Business District', 'Tourist District', 'Residential Area', 'Industrial Zone'],
  communities: ['Green Valley', 'Central Business', 'Tourist Hub', 'Sunset Hills', 'Riverside Park']
};

