export const INITIAL_COLUMNS = [
  { key: 'task', label: 'TASK' },
  { key: 'referenceNumber', label: 'REFERENCE NUMBER' },
  { key: 'category', label: 'TASK CATEGORY' },
  { key: 'status', label: 'STATUS' },
  { key: 'owner', label: 'OWNER' },
  { key: 'timeline', label: 'TIMELINE' },
  { key: 'planDays', label: 'PLAN DAYS' },
  { key: 'remarks', label: 'REMARKS' },
  { key: 'assigneeNotes', label: 'ASSIGNEE NOTES' },
  { key: 'attachments', label: 'ATTACHMENTS' },
  { key: 'priority', label: 'PRIORITY' },
  { key: 'location', label: 'LOCATION' },
  { key: 'plotNumber', label: 'PLOT NUMBER' },
  { key: 'community', label: 'COMMUNITY' },
  { key: 'projectType', label: 'PROJECT TYPE' },
  { key: 'projectFloor', label: 'PROJECT FLOOR' },
  { key: 'developerProject', label: 'DEVELOPER PROJECT' },
  { key: 'autoNumber', label: 'AUTO #' },
  { key: 'predecessors', label: 'PREDECESSORS' },
  { key: 'checklist', label: 'CHECKLIST' },
  { key: 'link', label: 'LINK' },
  { key: 'rating', label: 'RATING' },
  { key: 'progress', label: 'PROGRESS' },
  { key: 'color', label: 'COLOR' },
  { key: 'delete', label: '' }
];

